# Generated by Django 2.0.6 on 2018-08-17 06:55

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('active', models.CharField(max_length=1)),
                ('card_image', models.CharField(blank=True, default='cv-card-default.jpg', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.TextField(blank=True, null=True)),
                ('active', models.CharField(default='Y', max_length=1)),
                ('gender', models.CharField(default='Y', max_length=1)),
                ('date_birth', models.DateField(blank=True, default=datetime.datetime(2018, 8, 17, 6, 55, 42, 553135, tzinfo=utc))),
                ('card_image', models.CharField(blank=True, default='person-card-default.jpg', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('descr', models.TextField(blank=True, null=True)),
                ('active', models.CharField(default='Y', max_length=1)),
                ('date_start', models.DateField(blank=True, default=datetime.datetime(2018, 8, 17, 6, 55, 42, 553956, tzinfo=utc))),
                ('date_end', models.DateField(blank=True, default=datetime.datetime(2018, 8, 17, 6, 55, 42, 553975, tzinfo=utc))),
                ('card_image', models.CharField(blank=True, default='project-card-default.jpg', max_length=100, null=True)),
                ('cv', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='app.CV')),
                ('person', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='app.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('descr', models.TextField(blank=True, null=True)),
                ('active', models.CharField(default='Y', max_length=1)),
                ('card_image', models.CharField(blank=True, default='skill-card-default.jpg', max_length=100, null=True)),
                ('skill_level', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('person', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='app.Person')),
            ],
        ),
        migrations.CreateModel(
            name='SkillGroup',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('descr', models.TextField(blank=True, null=True)),
                ('active', models.CharField(default='Y', max_length=1)),
                ('card_image', models.CharField(blank=True, default='skillgroup-card-default.jpg', max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='skill',
            name='skillgroup',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='app.SkillGroup'),
        ),
        migrations.AddField(
            model_name='cv',
            name='person',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='app.Person'),
        ),
    ]
