# Generated by Django 2.0.6 on 2018-08-17 06:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='date_birth',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 8, 17, 6, 56, 9, 556236, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_end',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 8, 17, 6, 56, 9, 557091, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_start',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 8, 17, 6, 56, 9, 557072, tzinfo=utc)),
        ),
    ]
