# Generated by Django 2.0.6 on 2018-08-17 14:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180817_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='cv',
            field=models.ManyToManyField(to='app.CV'),
        ),
        migrations.AlterField(
            model_name='person',
            name='date_birth',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 8, 17, 14, 59, 13, 952072, tzinfo=utc)),
        ),
        migrations.RemoveField(
            model_name='project',
            name='cv',
        ),
        migrations.AddField(
            model_name='project',
            name='cv',
            field=models.ManyToManyField(to='app.CV'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_end',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 8, 17, 14, 59, 13, 952953, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_start',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 8, 17, 14, 59, 13, 952935, tzinfo=utc)),
        ),
    ]
