# Generated by Django 2.0.6 on 2018-08-17 14:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180817_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='date_birth',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 8, 17, 14, 59, 23, 24211, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_end',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 8, 17, 14, 59, 23, 25070, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_start',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 8, 17, 14, 59, 23, 25051, tzinfo=utc)),
        ),
    ]
